import React, { useEffect, useState } from 'react';
import api from '@shared/lib/api';
import toast from 'react-hot-toast';

type Role = { _id: string; name: string; category: string };
type Person = { _id: string; name: string; email: string };
type Assignment = { _id: string; principalType: string; roles: Role[]; active: boolean; expiresAt?: string | null };

export default function AccessControl() {
  const [roles, setRoles] = useState<Role[]>([]); const [users, setUsers] = useState<Person[]>([]); const [agents, setAgents] = useState<Person[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]);
  const [form, setForm] = useState({ principal: '', principalType: 'Agent', roles: [] as string[], expiresAt: '' });
  const load = async () => { try { const [r, u, a, x] = await Promise.all([api.get('/admin/roles'), api.get('/admin/users', { params: { limit: 200 } }), api.get('/admin/agents'), api.get('/rbac/assignments')]); setRoles(r.data.items || []); setUsers(u.data.items || []); setAgents(a.data.items || []); setAssignments(x.data.items || []); } catch { toast.error('Unable to load access control data'); } };
  useEffect(() => { load(); }, []);
  const principals = form.principalType === 'Agent' ? agents : users;
  const submit = async (e: React.FormEvent) => { e.preventDefault(); try { await api.post('/rbac/assignments', { ...form, expiresAt: form.expiresAt || null }); toast.success('Access assignment created'); setForm({ principal: '', principalType: 'Agent', roles: [], expiresAt: '' }); load(); } catch (error: any) { toast.error(error.response?.data?.message || 'Unable to create assignment'); } };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Access Control</h1><p className="text-sm text-gray-500">Assign multiple roles with an optional expiry. Permissions are evaluated with role and module scope.</p></div><form onSubmit={submit} className="card p-6 grid gap-4 md:grid-cols-2"><select className="input-field" value={form.principalType} onChange={e => setForm({ ...form, principalType: e.target.value, principal: '' })}><option value="Agent">Agent / internal user</option><option value="User">Customer / requester</option></select><select required className="input-field" value={form.principal} onChange={e => setForm({ ...form, principal: e.target.value })}><option value="">Select person</option>{principals.map(p => <option key={p._id} value={p._id}>{p.name} ({p.email})</option>)}</select><select multiple required className="input-field min-h-32" value={form.roles} onChange={e => setForm({ ...form, roles: Array.from(e.currentTarget.selectedOptions, o => o.value) })}>{roles.map(r => <option key={r._id} value={r._id}>{r.name} · {r.category}</option>)}</select><input className="input-field" type="datetime-local" value={form.expiresAt} onChange={e => setForm({ ...form, expiresAt: e.target.value })} /><button className="btn-primary md:col-span-2">Grant access</button></form><div className="card overflow-hidden"><table className="min-w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Principal</th><th className="p-3 text-left">Roles</th><th className="p-3 text-left">Expiry</th><th className="p-3 text-left">Status</th></tr></thead><tbody>{assignments.map(a => <tr key={a._id} className="border-t"><td className="p-3">{a.principalType}</td><td className="p-3">{a.roles?.map(r => r.name).join(', ')}</td><td className="p-3">{a.expiresAt ? new Date(a.expiresAt).toLocaleString() : 'No expiry'}</td><td className="p-3">{a.active ? 'Active' : 'Disabled'}</td></tr>)}</tbody></table></div></div>;
}
